spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/serdarceran/config-repo

server:
  port: ${vcap.application.port:9008}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
